### ISSUE TITLE
Cache build artefacts in CI

### ISSUE THREAD

**Issue by bfollington** [subconsciousnetwork/subconscious#459]
We could cut the overall CI pipeline time down considerably by caching the intermediate build results and then only rebuilding changed files since the last invocation.

ChatGPT seems to think this is pretty easy, unsure if it actually works:

```yaml
- name: Cache Xcode build artifacts
  uses: actions/cache@v2
  with:
    path: ~/Library/Developer/Xcode/DerivedData
    key: ${{ runner.os }}-xcode-${{ hashFiles('**/Podfile.lock') }}
    restore-keys: |
      ${{ runner.os }}-xcode-
```
